services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: taxcalculator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  migrate:
    build: .
    container_name: migrations
    entrypoint: ["/app/efbundle"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=taxcalculator;Username=postgres;Password=postgres"

  app:
    build: .
    container_name: tax-calculator
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=taxcalculator;Username=postgres;Password=postgres"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      migrate:
        condition: service_completed_successfully

  e2e-tests:
    profiles: ["e2e"]
    build:
      dockerfile: Dockerfile.playwright
      context: .
    container_name: e2e-tests
    depends_on:
      app:
        condition: service_healthy


volumes:
  postgres_data:
