name: Deploy 

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml
  
  deploy:
    name: Deploy to Fly.io
    needs: validate
    runs-on: ubuntu-latest
    concurrency: deploy-group  # ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy --remote-only --strategy=immediate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
