name: Validate

on:
  workflow_call:

jobs:
  backend-tests:
    name: Unit Tests - C# 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: dotnet restore backend/TaxCalculator.sln
        
      - name: Build
        run: dotnet build backend/TaxCalculator.sln --no-restore
        
      - name: Test
        run: dotnet test backend/TaxCalculator.sln --no-build --verbosity normal
  
  
  e2e-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Run E2E tests with Docker Compose
        run: docker compose run --rm e2e
